# Generated by Django 5.0.6 on 2024-05-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedstock',
            name='name',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
